### PR TITLE
Ngen.dev pet

### PR DESCRIPTION
**Pull request by champham**
Add integration test for running PET module.

## Additions

-

## Removals

-

## Changes

-

## Testing

1.

## Notes

-

## Todos

-

## Checklist

- [ ] PR has an informative and human-readable title
- [ ] Changes are limited to a single goal (no scope creep)
- [ ] Code can be automatically merged (no conflicts)
- [ ] Code follows project standards (link if applicable)
- [ ] Passes all existing automated tests
- [ ] Any _change_ in functionality is tested
- [ ] New functions are documented (with a description, list of inputs, and expected output)
- [ ] Placeholder code is flagged / future todos are captured in comments
- [ ] Project documentation has been updated (including the "Unreleased" section of the CHANGELOG)
- [ ] Reviewers requested with the [Reviewers tool](https://help.github.com/articles/requesting-a-pull-request-review/) :arrow_right:

## Testing checklist (automated report can be put here)

1.

### Target Environment support

- [x ] Linux

### CODE REVIEW

**Comment by stcui007** [comment]
I resolved some conflicts with master which resulted in the latest commit. Despite passing all the checks, the module_integration.yml code may have following issues:
From line 40 - 88, there appear to be indentation errors.
Between line 89 - 110, do we want to cache evapotranspiration as for CFE?

**Comment by donaldwj** [comment]
One problem I see is you have merge commit in your git history which means this can not be added to OWP/master. The branch would need to be rebased on OWP/master instead. This is so OWP/master always has a consistent history.

**Review by donaldwj — CHANGES_REQUESTED** [review]
One problem is there is a merge commit in history for this pull request. To merge this the code branch should be rebased on OWP/master instead of a merge being used.

**Comment by stcui007** [comment]
This PR has been replaced by #429

**Pull request closed without merging**
