### PR TITLE
catch formulation errors and report feature and timestep

### PR DESCRIPTION
**Pull request by hellkite500**
Addressing #777, this PR adds a `try/catch` to intercept `State_Exception`s thrown by formulations and adds the feature id and timestep the exception occurred at in the exception message.

## Changes

- Formulation calls to `get_response` are now wrapped with `try/catch`

## Checklist

- [x] PR has an informative and human-readable title
- [x] Changes are limited to a single goal (no scope creep)
- [x] Code can be automatically merged (no conflicts)
- [x] Code follows project standards (link if applicable)
- [x] Passes all existing automated tests
- [x] Any _change_ in functionality is tested
- [x] New functions are documented (with a description, list of inputs, and expected output)
- [x] Placeholder code is flagged / future todos are captured in comments
- [x] Project documentation has been updated (including the "Unreleased" section of the CHANGELOG)
- [x] Reviewers requested with the [Reviewers tool](https://help.github.com/articles/requesting-a-pull-request-review/) :arrow_right:

### Target Environment support

- [x] Linux
- [x] MacOS

### CODE REVIEW

**Comment by PhilMiller** [comment]
This looks like it'll work fine, but wouldn't it make more sense inside `get_response`?

**Comment by hellkite500** [comment]
I thought about that, but it would end up pretty heavily duplicated across the various BMI formulation implementations.  Additionally, I have been looking at refactoring the connection of Formulations with Catchments, which would potentially remove the feature identity from the Formulation inheritance hierarchy. So I thought this would be a good place for now since this is essentially the time/feature entry point to the formulation and all the required information is available to report when something goes wrong.

**Comment by PhilMiller** [comment]
Maybe this is the occasion to refactor those BMI formulation implementations to de-duplicate `get_response`, since none of its logic is or should be dependent on the underlying language of the BMI module.

**Comment by hellkite500** [comment]
I have a working branch where I've started down that path (and ended up doing the config refactoring to clean up the Formulation manager to help).  `get_response` is a bit of the legacy API carried around between the `Formulation` and the `Catchment` abstractions that I was aiming to declutter.  I would put it in that scope and try to leave this as a simple QoL update for error reporting/management (as long as the functionality here carries into future refactoring efforts).

**Comment by PhilMiller** [comment]
Ok, that's fair for now.

**Review by PhilMiller — APPROVED** [review]

**Pull request merged**
