### PR TITLE
Remove native/internal LSTM model

### PR DESCRIPTION
**Pull request by mattw-nws**
Builds on/requires #599

## Additions

- None

## Removals

- LSTM native/internal model, associated tests and data files.

## Changes

- Removals from some CMakeLists.txt files

## Testing

1. Passes all automated tests

## Notes

-

## Todos

-

## Checklist

- [X] PR has an informative and human-readable title
- [X] Changes are limited to a single goal (no scope creep)
- [X] Code can be automatically merged (no conflicts)
- [X] Code follows project standards (link if applicable)
- [X] Passes all existing automated tests
- [X] Any _change_ in functionality is tested
- [X] New functions are documented (with a description, list of inputs, and expected output)
- [X] Placeholder code is flagged / future todos are captured in comments
- [X] Project documentation has been updated (including the "Unreleased" section of the CHANGELOG)
- [X] Reviewers requested with the [Reviewers tool](https://help.github.com/articles/requesting-a-pull-request-review/) :arrow_right:

## Testing checklist (automated report can be put here)

1.

### Target Environment support

- [X] Linux

### CODE REVIEW

**Review by PhilMiller — APPROVED** [review]

**Comment by hellkite500** [comment]
Once we get all these deprecations in place, we should ensure each is represented in a single commit, then document the commit and the deprecation in a changelog.

**Review by PhilMiller — APPROVED** [review]

**Comment by jmframe** [comment]
Looks like this removes the C++ LSTM. Have y'all been running this version? If so, were you also running the Python version? Just out of curiosity.

**Comment by mattw-nws** [comment]
@jmframe No, we haven't in a long time, that's part of the reason for the removal--I'm not even sure if it still works. The API around the formulations has been evolving and we kept having to come back to the old non-BMI models and do a lot of retrofitting--so for the time being we're removing them to streamline things, because that API is probably going to need to further evolve quite a bit for a while to deal with multiple discretizations (structured grid models, catchment models, network/routing modules, unstructured grid models...).

I think there's space for non-BMI formulations in the future for various reasons including performance optimization (relevant to LSTM, probably), but the technical debt associated with the upkeep of things that weren't directly related to the capabilities we're being asked to develop was becoming costly. I'd like this to come back in the future after the internal APIs have stabilized more.

**Comment by mattw-nws** [comment]
Oh.. above was WRT the C version. The Python/BMI version is still being kept up by the formulations team and I think they're trying to build some model pieces to produce non-streamflow variables alongside it when it is used, for instance.

**Comment by jmframe** [comment]
Sounds good. That's what I figured.

**Pull request merged**
