### PR TITLE
Removes top-level tshirt models

### PR DESCRIPTION
**Pull request by mattw-nws**
Builds on/requires #595

Removes tshirt, tshirt_c, associated data and test files, and the Bmi_C_Cfe_IT test (which depended on tshirt).

## Additions

- None

## Removals

- tshirt, tshirt_c, associated data and test files, and the Bmi_C_Cfe_IT test (which depended on tshirt).

## Changes

- CMakeLists.txt removals for the legacy components, e.g. the `compare_cfe` target is now gone.

## Testing

1.

## Notes

-

## Todos

- Documentation and example file revisions will wait till the end of the PR chain

## Checklist

- [X] PR has an informative and human-readable title
- [X] Changes are limited to a single goal (no scope creep)
- [X] Code can be automatically merged (no conflicts)
- [X] Code follows project standards (link if applicable)
- [X] Passes all existing automated tests
- [X] Any _change_ in functionality is tested
- [X] New functions are documented (with a description, list of inputs, and expected output)
- [X] Placeholder code is flagged / future todos are captured in comments
- [X] Project documentation has been updated (including the "Unreleased" section of the CHANGELOG)
- [X] Reviewers requested with the [Reviewers tool](https://help.github.com/articles/requesting-a-pull-request-review/) :arrow_right:

## Testing checklist (automated report can be put here)

1.

### Target Environment support

- [X] Linux

### CODE REVIEW

**Comment by PhilMiller** [comment]
This looks good to me once the predecessors are merged and this gets rebased.

**Comment by mattw-nws** [comment]
It is worth pointing out that these legacy formulations (including LSTM) are

**Comment by mattw-nws** [comment]
It is worth pointing out that my trackpad is garbage.

**Comment by mattw-nws** [comment]
It is worth pointing out that these legacy formulations (including LSTM) are responsible for the essentially broken behavior of all current forcing providers that implement `get_data_start_time` and `get_data_end_time` --they are given and provide back the _simulation_ start and end time and nothing to do with the forcing data. The legacy formulations were (are) getting their simulation start and end times this way, so it couldn't be changed to more reasonable behavior. Now this is somewhat of a sticking point in #601 , or at least there's not a clean way to fix Bmi_Multi_Formulation's use of the same methods. Just one more reason to do this.

**Comment by PhilMiller** [comment]
I'm +1 once 595 is merged (and hence 594 before it)

**Review by robertbartel — DISMISSED** [review]

**Pull request closed without merging**
