### PR TITLE
Add UDUNITS_ACTIVE to build runners

### PR DESCRIPTION
**Pull request by mattw-nws**
[Short description explaining the high-level reason for the pull request]

## Additions

-

## Removals

-

## Changes

-

## Testing

1.

## Notes

-

## Todos

-

## Checklist

- [ ] PR has an informative and human-readable title
- [ ] Changes are limited to a single goal (no scope creep)
- [ ] Code can be automatically merged (no conflicts)
- [ ] Code follows project standards (link if applicable)
- [ ] Passes all existing automated tests
- [ ] Any _change_ in functionality is tested
- [ ] New functions are documented (with a description, list of inputs, and expected output)
- [ ] Placeholder code is flagged / future todos are captured in comments
- [ ] Project documentation has been updated (including the "Unreleased" section of the CHANGELOG)
- [ ] Reviewers requested with the [Reviewers tool](https://help.github.com/articles/requesting-a-pull-request-review/) :arrow_right:

## Testing checklist (automated report can be put here)

1.

### Target Environment support

- [ ] Linux

### CODE REVIEW

**Comment by mattw-nws** [comment]
See also 1624ccbd3fcf4be57de290c00ed9a9630c3387ec

**Review by robertbartel — COMMENTED** [review]
@mattw-nws I have a few things I'm curious about. 

First, this seems to be applicable to something that isn't yet committed to `master` (I see now that's probably #323).  Why separate this from the related set of changes?

Second, I think this adds `UDUNITS_ACTIVE` to the generated CMake build for every runner job, and I would have expected UDUnits to be a required dependency.   So why does there needs to be a CMake variable; is switching off `UDUNITS_ACTIVE`  a valid use case?  If so, is/will there be a separate suite of tests for those scenarios?

**Comment by mattw-nws** [comment]
[First:] Yep, the builders won't run to pass #323 (draft) until this is in place, but once it is, they _should_ pass, which breaks the paradox.

[Second:] Yes, I thought it possibly worth making it a configurable dependency for at least two scenarios, A: we might have another option in the future or a more basic one built in without a dependency, or B: allow builld without unit conversion support which would just passthrough values, which might be valid and simpler for some research scenarios. We could alternatively make it configurable but enabled by default like Python is currently, but even Python has the switch specified in the runners... I thought it better to be explicit.

**Comment by mattw-nws** [comment]
(addendum to [First] above: I'm pretty sure the workflows will only run the configuration in `master`, not what's in the PR branch...hence why to separate it.)

**Comment by robertbartel** [comment]
> (addendum to [First] above: I'm pretty sure the workflows will only run the configuration in `master`, not what's in the PR branch...hence why to separate it.)

@mattw-nws Ah, I see, though [I don't think this is correct](https://docs.github.com/en/actions/learn-github-actions/events-that-trigger-workflows#pull_request).   See item number 3 toward the bottom of [this section](https://docs.github.com/en/actions/learn-github-actions/events-that-trigger-workflows#example-using-multiple-events-with-activity-types-or-configuration) also.  It runs on the branch triggering the run, and the workflow config is part of the branch.

An experiment testing the behavior for this case might not be a bad idea.

**Comment by mattw-nws** [comment]
It appears as though it doesn't work... I just added 282aca5 to #323 and the builds still fail with a missing udunits2.h file.

**Comment by mattw-nws** [comment]
Correction (late), it does work, the failure was for a different reason after that.

**Pull request closed without merging**
