### PR TITLE
Modify Formulation_Manager.hpp to parse forcing "file_pattern"

### PR DESCRIPTION
**Pull request by stcui007**
This commit enable ngen to parse forcing "file_pattern" in explicit catchments formulation.

## Additions

data/test_bmi_multi_realization_config.json
data/test_bmi_multi_realization_config_w_netcdf.json
data/test_bmi_multi_realization_config_w_noah_pet_cfe.json
data/test_realization_config.json

## Removals

-

## Changes

include/realizations/catchment/Formulation_Manager.hpp

## Testing

unit tests
run ngen tests in serial
run ngen tests in parallel

## Notes

-

## Todos

-

## Checklist

- [x ] PR has an informative and human-readable title
- [x ] Changes are limited to a single goal (no scope creep)
- [x ] Code can be automatically merged (no conflicts)
- [x ] Code follows project standards (link if applicable)
- [ ] Passes all existing automated tests
- [ ] Any _change_ in functionality is tested
- [ ] New functions are documented (with a description, list of inputs, and expected output)
- [ ] Placeholder code is flagged / future todos are captured in comments
- [ ] Project documentation has been updated (including the "Unreleased" section of the CHANGELOG)
- [ ] Reviewers requested with the [Reviewers tool](https://help.github.com/articles/requesting-a-pull-request-review/) :arrow_right:

## Testing checklist (automated report can be put here)

1.

### Target Environment support

- [x ] Linux

### CODE REVIEW

**Comment by mattw-nws** [comment]
This looks promising... I will try testing with the files tomorrow... could you try adding an automated test for this? Would probably make sense in `Formulation_Manager_Test.cpp`.

**Comment by stcui007** [comment]
Yes, sure.

**Review by hellkite500 — CHANGES_REQUESTED** [review]
Generally looks good to me.  Doesn't change the existing semantics but allows significant code reuse!  My only concern is the test coverage now doesn't consider the case when an explicit path is passed.

**Comment by stcui007** [comment]
If there is no disagreement, I'll implement Nels' suggestion.

**Review by hellkite500 — APPROVED** [review]

**Pull request merged**
