### PR TITLE
Changes to integrate t-route master branch

### PR DESCRIPTION
**Pull request by mattw-nws**
`Routing_Py_Adapter` now attempts to run the master branch `main_v04` method if the legacy `ngen_routing` module is not found (this is not preference ordering, rather is the easiest way to determine which of the two is installed), so either version is runnable. Notably, however, all automated test code now tests the master branch and not the legacy ngen branch!

## Additions

- Code to run the new master branch `main_v04` method in t-route
- A test case to use on with the master branch

## Removals

- Unit test for legacy ngen branch version of t-route... while still possible to use, it is no longer integration tested!

## Changes

-

## Testing

1. Automated tests passing
2. Included somewhat complex test case in `data/gauge_01073000`, which successfully produces output.

## Notes

-

## Todos

- Eventually, the legacy ngen branch support should be removed.

## Checklist

- [X] PR has an informative and human-readable title
- [X] Changes are limited to a single goal (no scope creep)
- [X] Code can be automatically merged (no conflicts)
- [X] Code follows project standards (link if applicable)
- [X] Passes all existing automated tests
- [X] Any _change_ in functionality is tested
- [X] New functions are documented (with a description, list of inputs, and expected output)
- [X] Placeholder code is flagged / future todos are captured in comments
- [X] Project documentation has been updated (including the "Unreleased" section of the CHANGELOG)
- [X] Reviewers requested with the [Reviewers tool](https://help.github.com/articles/requesting-a-pull-request-review/) :arrow_right:

## Testing checklist (automated report can be put here)

1.

### Target Environment support

- [X] Linux

### CODE REVIEW

**Comment by mattw-nws** [comment]
@hellkite500 @donaldwj @robertbartel  ... maybe @shorvath-noaa and @kumdonoaa ... Before I fix the last test...

With this PR the ngen code itself can now--for now--work with either the old legacy ngen_main t-route code or the new nwm_routing module. This is particularly for use cases where old configs exist, I'm thinking particularly of the calibration work. The question is, what, if anything, should we do with `extern/t-route`? Should I bump it to t-route:master? Should I leave it in place for now pointing to the ngen branch (we may or may not want to bump the commit in that branch)? Should I remove it entirely?

My inclination is to encourage the build/installation of t-route separately going forward, especially since ngen will find it as long as it's installed (doesn't have to be in a particular dir, like the other modules in `extern`...or at least more so). So what to do with `extern/t-route`?

**Comment by kumdonoaa** [comment]
@mattw-nws  Just trying to understand what bumping it to t-route:master means, can you explain what changes would or should be made from the action and what results would come in terms of running t-route. Thanks.

**Comment by mattw-nws** [comment]
> @mattw-nws Just trying to understand what bumping it to t-route:master means

Sure, it's basically only a matter of what version of t-route we are "bundling" (in source form) with ngen, if any... we have previously been including the t-route source as a git submodule inside the ngen repo... the question is whether we should continue doing that and what version if any.

**Comment by mattw-nws** [comment]
Related question... should we keep the troute integration test in the ngen repo... or make a test for ngen integration in the t-route repo... or other?

**Comment by kumdonoaa** [comment]
Regarding the troute integration test, I feel that we need a meeting where Sean first demonstrates the progress of implementing BMI to t-route and reservoir modules so that you can give us feedbacks on whether we're on a right track or not.   After that, it would be great to show us how it looks like to do the integration test from ngen side and what are required.  Would that be a good starting point?

**Comment by mattw-nws** [comment]
This now needs https://github.com/NOAA-OWP/t-route/pull/606 to merge before the macOS routing test will pass, I think.

**Comment by mattw-nws** [comment]
Believe that when [t-route/#606](https://github.com/NOAA-OWP/t-route/pull/606) is merged, the failing macOS test may fix itself... if not some small change may be required here, but everything is failing that test ATM.

**Review by donaldwj — APPROVED** [review]
Almost completely configuration file changes. We may want to document the changes in the pull request page

**Pull request merged**
