### PR TITLE
Precision_Guidelines_for_Ngen_Code_Validation

### PR DESCRIPTION
**Pull request by stcui007**
A description on what to expect after a major Ngen code change or update.
Document in pdf format.

### CODE REVIEW

**Comment by hellkite500** [comment]
Nice write up! I think it we should dump this into markdown so we can version the document. We can always use pandoc to generate a pdf from the markdown. This will also help keep the history/repo size down.

**Comment by hellkite500** [comment]
I also want discuss a bit about the precip variable sometime.

**Comment by stcui007** [comment]
I haven't used markdown before. What do we need to do to dump the document to markdown?

About precip variable discussion, anytime would be fine.

**Comment by ZacharyWills** [comment]
Here's a useful tutorial for MD:

https://www.markdowntutorial.com/

**Comment by stcui007** [comment]
How do I preview my markdown document?

**Comment by stcui007** [comment]
Thanks Zach. 
I was able to change the document to the markdown format and upload it (PR#226). It looks ok.

**Comment by hellkite500** [comment]
closing in favor of #226

**Pull request closed without merging**
