### PR TITLE
Update data README and clean up contents of data folder

### PR DESCRIPTION
**Pull request by dblodgett-usgs**
This PR adds significant context regarding how the framework will relate to a "reference" domain and (a set of) "model" domains. I may be a bit off base in what's really needed in the data folder with regard to actual run-time data dependencies, but I think the changes I made here area step in the right direction.

## Additions

- added information about the data model scheme regarding parameters

## Removals

- removed unused original data files

## Changes

- I moved the sugar_creek folder contents out to the data folder

## Testing

1. None.

## Screenshots

See PR contents

## Notes

-

## Todos

-

## Checklist

- [x] PR has an informative and human-readable title
- [x] Changes are limited to a single goal (no scope creep)
- [x] Code can be automatically merged (no conflicts)
- [x] Code follows project standards (link if applicable)
- [x] Passes all existing automated tests
- [x] Any _change_ in functionality is tested
- [x] New functions are documented (with a description, list of inputs, and expected output)
- [x] Placeholder code is flagged / future todos are captured in comments
- [ ] Project documentation has been updated (including the "Unreleased" section of the CHANGELOG)
- [ ] Reviewers requested with the [Reviewers tool](https://help.github.com/articles/requesting-a-pull-request-review/) :arrow_right:

### CODE REVIEW

**Comment by hellkite500** [comment]
Way to go @dblodgett-usgs, seg fault the tests 😄.

@robertbartel Looks like some data changes are killing the GIUH reader in an unexpected way.  If you don't have a good idea off the top of your head, I'll look into it more but it will be a few days before I can.

**Comment by hellkite500** [comment]
Tests fixed here: https://github.com/dblodgett-usgs/ngen/pull/1. If you merge that PR @dblodgett-usgs, the commit should show up here.

**Comment by dblodgett-usgs** [comment]
Yes -- @hellkite500 -- I was just bringing the actual demo data up to a more prominent place.

**Comment by dblodgett-usgs** [comment]
ok -- merged.

**Pull request merged**
